### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zyg0t** [I-A-C/zips#6]
The dependency on script.module.idna version 2.6 could not be satisfied.

This is the error that shows up when I try to install Exodus Redux

**Comment by beznac** [comment]
So I found the solution to the problem. You have to install the IDNA Module manually, because it's shown as unavailable in the repository menu. You can install it from here:

https://github.com/Freso/script.module.idna

I also attached a direct link to it
[script.module.idna-master.zip](https://github.com/I-A-C/zips/files/5898402/script.module.idna-master.zip)
